apiVersion: apps/v1
kind: Deployment
metadata:
  name: github_action_eks_project-deployment   # deployment name
spec:
  replicas: 2                        # number of pods
  selector:
    matchLabels:
      app: github_action_eks_project
  template:
    metadata:
      labels:
        app: github_action_eks_project
    spec:
      containers:
        - name: github_action_eks_project
          image: 228948463033.dkr.ecr.us-east-1.amazonaws.com/github_action_eks_project:latest
          ports:
            - containerPort: 3000
