apiVersion: v1
kind: Service
metadata:
  name: github_action_eks_project-service
spec:
  type: LoadBalancer
  selector:
    app: github_action_eks_project           # must match deployment labels
  ports:
    - port: 80                     # public port
      targetPort: 3000             # container port
