apiVersion: v1
kind: Service
metadata:
  name: github-action-eks-project-service   # underscores to hyphens
spec:
  type: LoadBalancer
  selector:
    app: github-action-eks-project           # must match deployment labels
  ports:
    - port: 80
      targetPort: 3000
