name: Build, Push & Auto-Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if missing
        run: |
          aws ecr describe-repositories --repository-names github_action_eks_project || \
          aws ecr create-repository --repository-name github_action_eks_project

      - name: Build, Tag & Push Docker image
        env:
          ECR_REGISTRY: 228948463033.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: github_action_eks_project
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name New-EKS-Cluster-cluster

          # Apply Deployment & Service
          kubectl apply -f deployment.yaml --validate=false
          kubectl apply -f service.yaml --validate=false

          # Force redeploy by updating annotation
          kubectl patch deployment github-action-eks-project-deployment \
            -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"redeploy-timestamp\":\"$(date +%s)\"}}}}}"

          # Wait for rollout to complete
          kubectl rollout status deployment/github-action-eks-project-deployment
